Quick Instructions
==================

1. Import sql samples from server and 
   AAC into your MySQL database

2. Open config.inc.php with notepad,
   scroll through the options. Set 
   the following:

   a) Data directory
   b) MySQL user and password
   c) Admin account
   d) Temple coordinates and town names
   e) Enable vocations you want to use



Edit this text in notes.inc